language: java

jdk:
  - openjdk12

script:
  - ./gradlew clean build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;

    export VERSION=`./gradlew properties -q | grep "appVersion:" | awk '{print $2}'`

    docker build -t robsonbittencourt/springboot-component-scan-poc:latest -t robsonbittencourt/springboot-component-scan-poc:${VERSION} . ;

    docker push docker.io/robsonbittencourt/springboot-component-scan-poc:latest ;

    docker push docker.io/robsonbittencourt/springboot-component-scan-poc:${VERSION} ;
    fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/